### ISSUE TITLE
Error on Buffer for big files

### ISSUE THREAD

**Issue by Judahh** [vimtor/action-zip#18]
If I zip a really big file I get this error:
```
Ready to zip ".next/ next/ dist/ public/ node_modules/ script/ package.json" into staging/1.0.0.zip
  - .next/
  - next/ (Not Found)
  - dist/ (Not Found)
  - public/
  - node_modules/
  - script/ (Not Found)
  - package.json
internal/buffer.js:68
    throw new ERR_OUT_OF_RANGE('value', range, value);
    ^
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 65535. Received 65844
    at checkInt (internal/buffer.js:68:11)
    at writeU_Int16LE (internal/buffer.js:718:3)
    at Buffer.writeUInt16LE (internal/buffer.js:726:10)
    at Object.toBinary (/__w/_actions/vimtor/action-zip/master/dist/index.js:1655:15)
    at Object.compressToBuffer (/__w/_actions/vimtor/action-zip/master/dist/index.js:1001:24)
    at Object.writeZip (/__w/_actions/vimtor/action-zip/master/dist/index.js:2536:23)
    at Object.104 (/__w/_actions/vimtor/action-zip/master/dist/index.js:[93](https://github.com/alphasistemas/portal/actions/runs/3176283289/jobs/5175400662#step:12:97):5)
    at __webpack_require__ (/__w/_actions/vimtor/action-zip/master/dist/index.js:22:30)
    at startup (/__w/_actions/vimtor/action-zip/master/dist/index.js:37:19)
    at /__w/_actions/vimtor/action-zip/master/dist/index.js:41:18 {
  code: 'ERR_OUT_OF_RANGE'
}
```

**Comment by stan-spotts** [comment]
I just got this error too
