### ISSUE TITLE
no such file or directory, stat '/home/runner/work/

### ISSUE THREAD

**Issue by GeluConstantin** [vimtor/action-zip#32]
Can you tell me why I get the error bellow?

Thank you

Run vimtor/action-zip@v1.1
  with:
    files: .
    recursive: false
    dest: deployments/deployments.zip
Ready to zip "." into deployments/deployments.zip
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/home/runner/work/Directory/Directory/venv/bin/python'
    at Object.statSync (node:fs:1583:3)
    at /home/runner/work/_actions/vimtor/action-zip/v1.1/dist/index.js:1733:20
    at Array.forEach (<anonymous>)
    at findSync (/home/runner/work/_actions/vimtor/action-zip/v1.1/dist/index.js:1730:29)
    at /home/runner/work/_actions/vimtor/action-zip/v1.1/dist/index.js:1734:38
    at Array.forEach (<anonymous>)
    at findSync (/home/runner/work/_actions/vimtor/action-zip/v1.1/dist/index.js:1730:29)
    at /home/runner/work/_actions/vimtor/action-zip/v1.1/dist/index.js:1734:38
    at Array.forEach (<anonymous>)
    at findSync (/home/runner/work/_actions/vimtor/action-zip/v1.1/dist/index.js:1730:29) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/runner/work/OP_BA_AZVCheck/OP_BA_AZVCheck/venv/bin/python'
}

**Comment by GeluConstantin** [comment]
If I delete the virtual environment folder venv it works.

I suppose there is a problem with the symbolic link venv/bin/python
